version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: hello
      POSTGRES_PASSWORD: piix
      POSTGRES_DB: hello
    ports:
      - 5432:5432
